--- # A Tweet2vec bidirectional network, 1 layer

name: "1 layer bidirectional sentiment model"

dataset: CMSUserInputDataset

type: Tweet2Vec_BiGRU

description: >
    Single layer bidirectional GRU network

hyperparameters:
  seq_length: 256
  embedding_dimension: 256
  hidden_states: 128
  num_classes: 4
  number_of_layers: 1
  classifier_layers: [4096, 2048]

training:
  optimizer:
    name: 'adam'
    learning_rate: 0.001
    optimizer_parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 0.00000001
  validation_interval: 5
  test_interval: 60
  e_mail_interval: 3600
  summary_span: 100000
  checkpoint_interval: 1800
  batch_size: 100
  validation_size: 100
  test_size: 1000
  epochs: 50
