
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER SPACE EVERY AT ON WEEKDAY MINUTE HOUR DAY MONTH\n    schedule : EVERY every_week\n             | EVERY every_day\n             | EVERY every_hour\n             | EVERY every_month\n             | EVERY every_minute\n    \n    every_minute : MINUTE\n    \n    every_month : MONTH ON DAY list AT time\n    \n    every_week : WEEKDAY AT time\n    \n    every_hour : HOUR ON MINUTE list\n    \n    every_day : DAY AT list\n              | DAY AT time\n    \n    list : '(' list_of_times ')'\n         | '(' list_of_numbers ')'\n    \n    list_of_numbers : list_of_numbers ',' NUMBER\n                    | NUMBER\n    \n    list_of_times : list_of_times ',' time\n                  | time\n    \n    time : NUMBER ':' NUMBER\n    "
    
_lr_action_items = {'ON':([6,7,],[13,14,]),',':([27,28,29,30,32,38,39,],[34,-15,-17,36,-18,-16,-14,]),'HOUR':([2,],[6,]),')':([27,28,29,30,32,38,39,],[33,-15,-17,35,-18,-16,-14,]),'(':([16,17,18,],[21,21,21,]),'NUMBER':([15,16,21,26,31,34,36,],[19,19,28,32,19,19,39,]),'MONTH':([2,],[7,]),'EVERY':([0,],[2,]),'WEEKDAY':([2,],[10,]),'AT':([10,11,25,33,35,],[15,16,31,-12,-13,]),':':([19,28,],[26,26,]),'DAY':([2,14,],[11,18,]),'MINUTE':([2,13,],[12,17,]),'$end':([1,3,4,5,8,9,12,20,22,23,24,32,33,35,37,],[0,-5,-3,-4,-1,-2,-6,-8,-10,-11,-9,-18,-12,-13,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'every_minute':([2,],[3,]),'every_hour':([2,],[4,]),'every_month':([2,],[5,]),'schedule':([0,],[1,]),'list_of_times':([21,],[27,]),'list':([16,17,18,],[22,24,25,]),'every_week':([2,],[8,]),'every_day':([2,],[9,]),'time':([15,16,21,31,34,],[20,23,29,37,38,]),'list_of_numbers':([21,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> schedule","S'",1,None,None,None),
  ('schedule -> EVERY every_week','schedule',2,'p_schedule','parser.py',80),
  ('schedule -> EVERY every_day','schedule',2,'p_schedule','parser.py',81),
  ('schedule -> EVERY every_hour','schedule',2,'p_schedule','parser.py',82),
  ('schedule -> EVERY every_month','schedule',2,'p_schedule','parser.py',83),
  ('schedule -> EVERY every_minute','schedule',2,'p_schedule','parser.py',84),
  ('every_minute -> MINUTE','every_minute',1,'p_every_minute','parser.py',91),
  ('every_month -> MONTH ON DAY list AT time','every_month',6,'p_every_month','parser.py',99),
  ('every_week -> WEEKDAY AT time','every_week',3,'p_every_week','parser.py',115),
  ('every_hour -> HOUR ON MINUTE list','every_hour',4,'p_every_hour','parser.py',127),
  ('every_day -> DAY AT list','every_day',3,'p_every_day','parser.py',136),
  ('every_day -> DAY AT time','every_day',3,'p_every_day','parser.py',137),
  ('list -> ( list_of_times )','list',3,'p_list','parser.py',155),
  ('list -> ( list_of_numbers )','list',3,'p_list','parser.py',156),
  ('list_of_numbers -> list_of_numbers , NUMBER','list_of_numbers',3,'p_list_of_numbers','parser.py',163),
  ('list_of_numbers -> NUMBER','list_of_numbers',1,'p_list_of_numbers','parser.py',164),
  ('list_of_times -> list_of_times , time','list_of_times',3,'p_list_of_times','parser.py',175),
  ('list_of_times -> time','list_of_times',1,'p_list_of_times','parser.py',176),
  ('time -> NUMBER : NUMBER','time',3,'p_time','parser.py',187),
]
