
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INT FLOAT STRING LPAREN RPAREN LBRACE RBRACE LBRACKET RBRACKET SYMBOL KEYWORDsexps : sexp sexpssexp : KEYWORD\n            | INT\n            | FLOAT\n            | STRING\n            | SYMBOL\n            sexp : LBRACKET sexps RBRACKET\n            sexp : LPAREN sexps RPARENsexp : LBRACE sexps RBRACEsexps : emptyempty :'
    
_lr_action_items = {'RBRACKET':([1,2,3,4,5,9,10,11,12,13,16,17,18,],[-5,-4,-11,-11,-10,-3,-2,-6,16,-1,-7,-9,-8,]),'STRING':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[1,-5,-4,1,1,1,1,-3,-2,-6,-7,-9,-8,]),'INT':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[9,-5,-4,9,9,9,9,-3,-2,-6,-7,-9,-8,]),'LBRACKET':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[3,-5,-4,3,3,3,3,-3,-2,-6,-7,-9,-8,]),'LBRACE':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[7,-5,-4,7,7,7,7,-3,-2,-6,-7,-9,-8,]),'LPAREN':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[8,-5,-4,8,8,8,8,-3,-2,-6,-7,-9,-8,]),'RPAREN':([1,2,4,5,8,9,10,11,13,15,16,17,18,],[-5,-4,-11,-10,-11,-3,-2,-6,-1,18,-7,-9,-8,]),'FLOAT':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[2,-5,-4,2,2,2,2,-3,-2,-6,-7,-9,-8,]),'KEYWORD':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[10,-5,-4,10,10,10,10,-3,-2,-6,-7,-9,-8,]),'RBRACE':([1,2,4,5,7,9,10,11,13,14,16,17,18,],[-5,-4,-11,-10,-11,-3,-2,-6,-1,17,-7,-9,-8,]),'$end':([0,1,2,4,5,6,9,10,11,13,16,17,18,],[-11,-5,-4,-11,-10,0,-3,-2,-6,-1,-7,-9,-8,]),'SYMBOL':([0,1,2,3,4,7,8,9,10,11,16,17,18,],[11,-5,-4,11,11,11,11,-3,-2,-6,-7,-9,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sexp':([0,3,4,7,8,],[4,4,4,4,4,]),'empty':([0,3,4,7,8,],[5,5,5,5,5,]),'sexps':([0,3,4,7,8,],[6,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sexps","S'",1,None,None,None),
  ('sexps -> sexp sexps','sexps',2,'p_program','_yacc.py',17),
  ('sexp -> KEYWORD','sexp',1,'p_sexp_atomic','_yacc.py',21),
  ('sexp -> INT','sexp',1,'p_sexp_atomic','_yacc.py',22),
  ('sexp -> FLOAT','sexp',1,'p_sexp_atomic','_yacc.py',23),
  ('sexp -> STRING','sexp',1,'p_sexp_atomic','_yacc.py',24),
  ('sexp -> SYMBOL','sexp',1,'p_sexp_atomic','_yacc.py',25),
  ('sexp -> LBRACKET sexps RBRACKET','sexp',3,'p_sexp','_yacc.py',33),
  ('sexp -> LPAREN sexps RPAREN','sexp',3,'p_sexp_list','_yacc.py',39),
  ('sexp -> LBRACE sexps RBRACE','sexp',3,'p_sexp_dict','_yacc.py',47),
  ('sexps -> empty','sexps',1,'p_sexps','_yacc.py',64),
  ('empty -> <empty>','empty',0,'p_empty','_yacc.py',69),
]
